# Data Quality Backtest Modelo Yastas

In [1]:
import pandas as pd
import numpy as np

In [2]:
parquet_junio = 'C:/Users/E-LHPEREZ/Desktop/Backtest Yastas/Backtest/SabanaAnalitica_MalasPracticasYastas_24ago26_junio26.parquet'
df_junio = pd.read_parquet(parquet_junio)

parquet_julio = 'C:/Users/E-LHPEREZ/Desktop/Backtest Yastas/Backtest/SabanaAnalitica_MalasPracticasYastas_24ago26_julio26.parquet'
df_julio = pd.read_parquet(parquet_julio)

In [3]:
def reporte_calidad_dataframe(df):
    """
    Analiza un DataFrame y devuelve un nuevo DataFrame con todas las métricas
    de calidad de datos agregadas por columna.
    """
    total_filas = df.shape[0]
    metricas = []

    for col in df.columns:
        # 1. Tipo de dato y conteos básicos
        tipo_dato = df[col].dtype
        nulos = df[col].isnull().sum()
        porc_nulos = round((nulos / total_filas) * 100, 2)
        unicos = df[col].nunique()
        porc_unicos = round((unicos / total_filas) * 100, 2)
        
        # Valores por defecto para variables no numéricas
        min_val = np.nan
        max_val = np.nan
        outliers_count = 0
        porc_outliers = 0.0

        # 2. Métricas y Outliers solo para columnas numéricas
        if pd.api.types.is_numeric_dtype(df[col]):
            min_val = df[col].min()
            max_val = df[col].max()
            
            # Cálculo IQR de Outliers
            col_sin_nulos = df[col].dropna()
            if len(col_sin_nulos) > 0:
                Q1 = col_sin_nulos.quantile(0.25)
                Q3 = col_sin_nulos.quantile(0.75)
                IQR = Q3 - Q1
                limite_inferior = Q1 - 1.5 * IQR
                limite_superior = Q3 + 1.5 * IQR
                
                outliers_count = ((df[col] < limite_inferior) | (df[col] > limite_superior)).sum()
                porc_outliers = round((outliers_count / total_filas) * 100, 2)

        # 3. Guardar registro por columna
        metricas.append({
            'columna': col,
            'tipo_dato': str(tipo_dato),
            'nulos_total': nulos,
            'nulos_porc': porc_nulos,
            'unicos_total': unicos,
            'unicos_porc': porc_unicos,
            'valor_min': min_val,
            'valor_max': max_val,
            'outliers_total': outliers_count,
            'outliers_porc': porc_outliers
        })

    # Convertimos a DataFrame
    df_reporte = pd.DataFrame(metricas)
    return df_reporte

## Ejecucion del data quality en parquet

### JUNIO

In [4]:
if __name__ == "__main__":
    parquet_dq_junio = reporte_calidad_dataframe(df_junio)

In [5]:
parquet_dq_junio

,columna,tipo_dato,nulos_total,nulos_porc,unicos_total,unicos_porc,valor_min,valor_max,outliers_total,outliers_porc
0,ID COMERCIO aux,float64,34,0.89,3775,98.85,0.0,25189.0,0,0.00
1,ID COB,float64,34,0.89,3785,99.11,19.0,23297.0,0,0.00
2,Num Comercios,float64,34,0.89,12,0.31,0.0,39.0,387,10.13
3,Ruta Yastás,string,45,1.18,80,2.09,NaN,NaN,0,0.00
4,Región Yastás,string,45,1.18,10,0.26,NaN,NaN,0,0.00
...,...,...,...,...,...,...,...,...,...,...
78,Tuvo_Alertas_Fracc,int64,0,0.00,2,0.05,0.0,1.0,111,2.91
79,Tuvo_Alertas_BE,float64,11,0.29,2,0.05,0.0,1.0,0,0.00
80,Tuvo_Alertas_Noche,float64,11,0.29,2,0.05,0.0,1.0,94,2.46
81,Tuve_Alertas_CDC,float64,11,0.29,2,0.05,0.0,1.0,165,4.32
82,Tuvo_Alertas_Malas_Practicas,float64,11,0.29,2,0.05,0.0,1.0,0,0.00

In [6]:
total_duplicados_junio = df_junio.duplicated().sum()
print(f"Total de filas duplicadas en la tabla: {total_duplicados_junio}")

Total de filas duplicadas en la tabla: 33

In [7]:
parquet_duplicados_junio = df_junio[df_junio.duplicated()]
parquet_duplicados_junio

,ID COMERCIO aux,ID COB,Num Comercios,Ruta Yastás,Región Yastás,Subdirección,Segmento,Nombre del Comercio,OS nombre,Transacciones,...,pct_monto_nocturno,ratio_monto_vs_red,zscore_nocturno_monto,monto_noc_vs_propio_diurno,tiempo_inactividad_diurna_hrs,Tuvo_Alertas_Fracc,Tuvo_Alertas_BE,Tuvo_Alertas_Noche,Tuve_Alertas_CDC,Tuvo_Alertas_Malas_Practicas
3786,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3787,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3788,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3789,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3790,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3791,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3792,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3793,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3794,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3795,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3796,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3797,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3798,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3799,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3800,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3801,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3802,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3803,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3804,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3805,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3806,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3807,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3808,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3809,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3810,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3811,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3812,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3813,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3814,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3815,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3816,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3817,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0
3818,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,0.0,0.0,-0.132,0.0,-1.0,0,0.0,0.0,0.0,0.0

In [8]:
# Opcional: Guardarlo a un archivo CSV o Excel
parquet_dq_junio.to_excel("reporte_calidad_Yastas_Backtest_parquet_junio.xlsx", index=False)

## Ejecucion del data quality en Excel

### JULIO

In [9]:
if __name__ == "__main__":
    parquet_dq_julio = reporte_calidad_dataframe(df_julio)

In [10]:
parquet_dq_julio

,columna,tipo_dato,nulos_total,nulos_porc,unicos_total,unicos_porc,valor_min,valor_max,outliers_total,outliers_porc
0,ID COMERCIO aux,int64,0,0.00,3809,99.82,0.0,25324.0,0,0.00
1,ID COB,int64,0,0.00,3816,100.00,19.0,23415.0,0,0.00
2,Num Comercios,int64,0,0.00,12,0.31,0.0,39.0,385,10.09
3,Ruta Yastás,string,9,0.24,80,2.10,NaN,NaN,0,0.00
4,Región Yastás,string,2167,56.79,10,0.26,NaN,NaN,0,0.00
...,...,...,...,...,...,...,...,...,...,...
78,Tuvo_Alertas_Fracc,int64,0,0.00,2,0.05,0.0,1.0,87,2.28
79,Tuvo_Alertas_BE,int64,0,0.00,2,0.05,0.0,1.0,0,0.00
80,Tuvo_Alertas_Noche,int64,0,0.00,2,0.05,0.0,1.0,131,3.43
81,Tuve_Alertas_CDC,int64,0,0.00,2,0.05,0.0,1.0,156,4.09
82,Tuvo_Alertas_Malas_Practicas,int64,0,0.00,2,0.05,0.0,1.0,0,0.00

In [11]:
total_duplicados_julio = df_julio.duplicated().sum()
print(f"Total de filas duplicadas en la tabla: {total_duplicados_julio}")

Total de filas duplicadas en la tabla: 0

In [12]:
parquet_duplicados_julio = df_julio[df_julio.duplicated()]
parquet_duplicados_julio

Empty DataFrame
Columns: [ID COMERCIO aux, ID COB, Num Comercios, Ruta Yastás, Región Yastás, Subdirección, Segmento, Nombre del Comercio, OS nombre, Transacciones, Txs Fraccionadas, Monto operado, Ganancias, Descuento mayor a $500, 10%+ Txs Fracc, 10%+ Monto Op Fracc, Pierde 10% ganancias, Total Alertas Fraccionadas, Txs 11pm a 6 am, Txs Fracc de 11pm a 6am, Monto Operado de 11pm a 6 am, Txs de CB de 11pm a 6 am, Monto Op CB de 11pm a 6 am, Realiza mas de 5 Txs CB, 10%+ Txs son fraccionadas (noche), 10%+ de sus Transacciones (noche), 10%+ de su Monto Operado (noche), Total Alertas Horarios, Txs Cob de Cobs, Monto Operado Cob de Cobs, Se invierte asi mismo, A cuantos comisionistas invierte, 10%+ monto operado es CdC, 10%+ Txs es CdC, Montos Operados Altos, Se Regresa la inversion, Usa txs para pagar BE, Total Alertas CdC, Txs con BE, Monto Operado con BE, Mas del 30% Txs con BE, Mas del 30% Monto con BE, Total Alertas BE, cuentas_destino_distintas, monto_saliente_cdc, txs_cdc_salientes, cuentas_origen_distintas, monto_entrante_cdc, txs_cdc_entrantes, ratio_circularidad_txs, ratio_circularidad_monto, tiempo_retorno_hrs_p50, flag_ciclo_24h, txs_borde_umbral, monto_borde_total, pct_txs_borde, coef_variacion_monto, entropy_monto, refs_unicas, txs_misma_ref_p95, ref_unicas_ratio, txs_ref_repetida, velocity_max_1h, velocity_max_3h, velocity_max_6h, velocity_max_12h, tiempo_promedio_entre_txs_seg, txs_rafaga_menor_60s, max_txs_mismo_monto, pct_txs_mismo_monto, txs_noc_dias_distintos, concentracion_hora_noc, pct_txs_nocturno, pct_monto_nocturno, ratio_monto_vs_red, zscore_nocturno_monto, monto_noc_vs_propio_diurno, tiempo_inactividad_diurna_hrs, Tuvo_Alertas_Fracc, Tuvo_Alertas_BE, Tuvo_Alertas_Noche, Tuve_Alertas_CDC, Tuvo_Alertas_Malas_Practicas]
Index: []

[0 rows x 83 columns]

In [13]:
# Opcional: Guardarlo a un archivo CSV o Excel
parquet_dq_julio.to_excel("reporte_calidad_Yastas_Backtest_parquet_julio.xlsx", index=False)