# VALIDACIÓN PROPENSIÓN A COMPRAS

In [1]:
import os
import pandas as pd
import numpy as np
import warnings
from datetime import datetime
import datetime as dt
from datetime import date, timedelta
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns',800)
pd.set_option('display.float_format',lambda x:'%.2f'%x)

## Lectura y carga de datos

In [2]:
sabana_opt = 'C:/Users/E-LHPEREZ/Desktop/Propension a compras/InsumoHana_SabanaAnalitica_PropCompras_09Sep2026_Jul26.parquet'
df_prcom_opt=pd.read_parquet(sabana_opt)
df_prcom_opt.shape

(2826198, 110)

In [3]:
sabana_orig = 'C:/Users/E-LHPEREZ/Desktop/Propension a compras/InsumoHana_SabanaAnalitica_PropCompras_12Aug2026_Jun26.parquet'
df_prcom_orig=pd.read_parquet(sabana_orig)
df_prcom_orig.shape

(2826168, 242)

In [4]:
print(df_prcom_opt['TOT_TX_OUT_M0'].isna().sum())

0

In [5]:
print(df_prcom_orig['TOT_TX_OUT_M0'].isna().sum())

452718

In [6]:
df_prcom_opt[df_prcom_opt['NUM_CLIENTE']==9143448]

,NUM_CLIENTE,CUENTA_AHORRO,ANTIGUEDAD_AHORRO,OFICINA_SERVICIO,SALDO_CORTE,SALDO_CORTE_AH_M0,SALDO_CORTE_AH_M1,SALDO_CORTE_AH_M2,SALDO_CORTE_AH_M3,SALDO_CORTE_AH_M4,SALDO_CORTE_AH_M5,SALDO_CORTE_AH_M6,SALDO_CORTE_AH_M7,SALDO_CORTE_AH_M8,SALDO_AH_M0,SALDO_AH_M1,SALDO_AH_M2,SALDO_AH_M3,SALDO_AH_M4,SALDO_AH_M5,SALDO_AH_M6,SALDO_AH_M7,SALDO_AH_M8,SALDO_INV_M0,SALDO_INV_M1,SALDO_INV_M2,SALDO_INV_M3,SALDO_INV_M4,SALDO_INV_M5,SALDO_INV_M6,SALDO_INV_M7,SALDO_INV_M8,MONTO_TX_IN_M0,MONTO_TX_IN_M1,MONTO_TX_IN_M2,MONTO_TX_IN_M3,MONTO_TX_IN_M4,MONTO_TX_IN_M5,MONTO_TX_IN_M6,MONTO_TX_IN_M7,MONTO_TX_IN_M8,TOT_TX_IN_M0,TOT_TX_IN_M1,TOT_TX_IN_M2,TOT_TX_IN_M3,TOT_TX_IN_M4,TOT_TX_IN_M5,TOT_TX_IN_M6,TOT_TX_IN_M7,TOT_TX_IN_M8,TOT_TX_OUT_M0,TOT_TX_OUT_M1,TOT_TX_OUT_M2,TOT_TX_OUT_M3,TOT_TX_OUT_M4,TOT_TX_OUT_M5,TOT_TX_OUT_M6,TOT_TX_OUT_M7,TOT_TX_OUT_M8,MONTO_SPEI_IN_M0,MONTO_SPEI_IN_M1,MONTO_SPEI_IN_M2,MONTO_SPEI_IN_M3,MONTO_SPEI_IN_M4,MONTO_SPEI_IN_M5,MONTO_SPEI_IN_M6,MONTO_SPEI_IN_M7,MONTO_SPEI_IN_M8,"COALESCE(TOT_SPEI_TX_IN_M0,0)","COALESCE(TOT_SPEI_TX_IN_M1,0)",MONTO_SPEI_OUT_M0,MONTO_SPEI_OUT_M1,MONTO_SPEI_OUT_M2,MONTO_SPEI_OUT_M3,MONTO_SPEI_OUT_M4,MONTO_SPEI_OUT_M5,MONTO_SPEI_OUT_M6,MONTO_SPEI_OUT_M7,MONTO_SPEI_OUT_M8,MONTO_DESEM_CRED_IN_M0,MONTO_DESEM_CRED_IN_M1,MONTO_DESEM_CRED_IN_M2,MONTO_DESEM_CRED_IN_M3,MONTO_DESEM_CRED_IN_M4,MONTO_DESEM_CRED_IN_M5,MONTO_DESEM_CRED_IN_M6,MONTO_DESEM_CRED_IN_M7,MONTO_DESEM_CRED_IN_M8,MONTO_COMPRAS_OUT_M0,MONTO_COMPRAS_OUT_M1,MONTO_COMPRAS_OUT_M2,MONTO_COMPRAS_OUT_M3,MONTO_COMPRAS_OUT_M4,MONTO_COMPRAS_OUT_M5,MONTO_COMPRAS_OUT_M6,MONTO_COMPRAS_OUT_M7,MONTO_COMPRAS_OUT_M8,"COALESCE(TOT_COMPRAS_TX_OUT_M0,0)","COALESCE(TOT_COMPRAS_TX_OUT_M1,0)","COALESCE(TOT_COMPRAS_TX_OUT_M2,0)","COALESCE(TOT_COMPRAS_TX_OUT_M3,0)","COALESCE(TOT_COMPRAS_TX_OUT_M4,0)","COALESCE(TOT_COMPRAS_TX_OUT_M5,0)","COALESCE(TOT_COMPRAS_TX_OUT_M6,0)","COALESCE(TOT_COMPRAS_TX_OUT_M7,0)","COALESCE(TOT_COMPRAS_TX_OUT_M8,0)",EDAD,HIJOS,CP,MONTO_DESEMBOLSO
210478,9143448,00187721470,23,30031153,185.76,185.76,185.72,185.72,185.64,185.60,185.60,185.52,185.48,185.48,185.75,185.72,185.68,185.63,185.60,185.56,185.51,185.48,185.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,46,4,27444,34003.85
2145668,9143448,00187722528,23,30031153,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,46,4,27444,34003.85

In [7]:
df_prcom_orig[df_prcom_orig['NUM_CLIENTE']== 9143448]

,NUM_CLIENTE,BP,NUM_CUENTA_AHORRO,ID_ESTATUS_CUENTA,ANTIGUEDAD_AHORRO,CUENTA_AHORRO,FEC_APERTURA_CUENTA,ESTATUS_CUENTA_DESC,ID_PRODUCTO_AHORRO,PRODUCTO_AHORRO,SALDO_CORTE,ESTATUS_PLASTICO_ID,ESTATUS_PLASTICO_DESC,FECHA_VIGENCIA_PLASTICO,FLAG_AMIFAVOR,FLAG_AHORROS,FLAG_INVERSIONES,FLAG_CRD,NUM_INVERSIONES,SALDO_CORTE_INVER,PLAZO,SALDO_CORTE_AH_M_2,SALDO_CORTE_AH_M_1,SALDO_CORTE_AH_M0,SALDO_CORTE_AH_M1,SALDO_CORTE_AH_M2,SALDO_CORTE_AH_M3,SALDO_CORTE_AH_M4,SALDO_CORTE_AH_M5,SALDO_CORTE_AH_M6,SALDO_CORTE_AH_M7,SALDO_CORTE_AH_M8,SALDO_AH_M_2,SALDO_AH_M_1,SALDO_AH_M0,SALDO_AH_M1,SALDO_AH_M2,SALDO_AH_M3,SALDO_AH_M4,SALDO_AH_M5,SALDO_AH_M6,SALDO_AH_M7,SALDO_AH_M8,SALDO_INV_CORTE_M_2,SALDO_INV_CORTE_M_1,SALDO_INV_CORTE_M0,SALDO_INV_CORTE_M1,SALDO_INV_CORTE_M2,SALDO_INV_CORTE_M3,SALDO_INV_CORTE_M4,SALDO_INV_CORTE_M5,SALDO_INV_CORTE_M6,SALDO_INV_CORTE_M7,SALDO_INV_CORTE_M8,SALDO_INV_M_2,SALDO_INV_M_1,SALDO_INV_M0,SALDO_INV_M1,SALDO_INV_M2,SALDO_INV_M3,SALDO_INV_M4,SALDO_INV_M5,SALDO_INV_M6,SALDO_INV_M7,SALDO_INV_M8,MONTO_TX_IN_M_2,TOT_TX_IN_M_2,MONTO_TX_IN_M_1,TOT_TX_IN_M_1,MONTO_TX_IN_M0,TOT_TX_IN_M0,MONTO_TX_IN_M1,TOT_TX_IN_M1,MONTO_TX_IN_M2,TOT_TX_IN_M2,MONTO_TX_IN_M3,TOT_TX_IN_M3,MONTO_TX_IN_M4,TOT_TX_IN_M4,MONTO_TX_IN_M5,TOT_TX_IN_M5,MONTO_TX_IN_M6,TOT_TX_IN_M6,MONTO_TX_IN_M7,TOT_TX_IN_M7,MONTO_TX_IN_M8,TOT_TX_IN_M8,MONTO_TX_OUT_M_2,TOT_TX_OUT_M_2,MONTO_TX_OUT_M_1,TOT_TX_OUT_M_1,MONTO_TX_OUT_M0,TOT_TX_OUT_M0,MONTO_TX_OUT_M1,TOT_TX_OUT_M1,MONTO_TX_OUT_M2,TOT_TX_OUT_M2,MONTO_TX_OUT_M3,TOT_TX_OUT_M3,MONTO_TX_OUT_M4,TOT_TX_OUT_M4,MONTO_TX_OUT_M5,TOT_TX_OUT_M5,MONTO_TX_OUT_M6,TOT_TX_OUT_M6,MONTO_TX_OUT_M7,TOT_TX_OUT_M7,MONTO_TX_OUT_M8,TOT_TX_OUT_M8,MONTO_SPEI_IN_M_2,TOT_SPEI_TX_IN_M_2,MONTO_SPEI_IN_M_1,TOT_SPEI_TX_IN_M_1,MONTO_SPEI_IN_M0,TOT_SPEI_TX_IN_M0,MONTO_SPEI_IN_M1,TOT_SPEI_TX_IN_M1,MONTO_SPEI_IN_M2,TOT_SPEI_TX_IN_M2,MONTO_SPEI_IN_M3,TOT_SPEI_TX_IN_M3,MONTO_SPEI_IN_M4,TOT_SPEI_TX_IN_M4,MONTO_SPEI_IN_M5,TOT_SPEI_TX_IN_M5,MONTO_SPEI_IN_M6,TOT_SPEI_TX_IN_M6,MONTO_SPEI_IN_M7,TOT_SPEI_TX_IN_M7,MONTO_SPEI_IN_M8,TOT_SPEI_TX_IN_M8,MONTO_SPEI_OUT_M_2,TOT_SPEI_TX_OUT_M_2,MONTO_SPEI_OUT_M_1,TOT_SPEI_TX_OUT_M_1,MONTO_SPEI_OUT_M0,TOT_SPEI_TX_OUT_M0,MONTO_SPEI_OUT_M1,TOT_SPEI_TX_OUT_M1,MONTO_SPEI_OUT_M2,TOT_SPEI_TX_OUT_M2,MONTO_SPEI_OUT_M3,TOT_SPEI_TX_OUT_M3,MONTO_SPEI_OUT_M4,TOT_SPEI_TX_OUT_M4,MONTO_SPEI_OUT_M5,TOT_SPEI_TX_OUT_M5,MONTO_SPEI_OUT_M6,TOT_SPEI_TX_OUT_M6,MONTO_SPEI_OUT_M7,TOT_SPEI_TX_OUT_M7,MONTO_SPEI_OUT_M8,TOT_SPEI_TX_OUT_M8,MONTO_DESEM_CRED_IN_M_2,TOT_DESEM_CRED_TX_IN_M_2,MONTO_DESEM_CRED_IN_M_1,TOT_DESEM_CRED_TX_IN_M_1,MONTO_DESEM_CRED_IN_M0,TOT_DESEM_CRED_TX_IN_M0,MONTO_DESEM_CRED_IN_M1,TOT_DESEM_CRED_TX_IN_M1,MONTO_DESEM_CRED_IN_M2,TOT_DESEM_CRED_TX_IN_M2,MONTO_DESEM_CRED_IN_M3,TOT_DESEM_CRED_TX_IN_M3,MONTO_DESEM_CRED_IN_M4,TOT_DESEM_CRED_TX_IN_M4,MONTO_DESEM_CRED_IN_M5,TOT_DESEM_CRED_TX_IN_M5,MONTO_DESEM_CRED_IN_M6,TOT_DESEM_CRED_TX_IN_M6,MONTO_DESEM_CRED_IN_M7,TOT_DESEM_CRED_TX_IN_M7,MONTO_DESEM_CRED_IN_M8,TOT_DESEM_CRED_TX_IN_M8,MONTO_COMPRAS_OUT_M_2,TOT_COMPRAS_TX_OUT_M_2,MONTO_COMPRAS_OUT_M_1,TOT_COMPRAS_TX_OUT_M_1,MONTO_COMPRAS_OUT_M0,TOT_COMPRAS_TX_OUT_M0,MONTO_COMPRAS_OUT_M1,TOT_COMPRAS_TX_OUT_M1,MONTO_COMPRAS_OUT_M2,TOT_COMPRAS_TX_OUT_M2,MONTO_COMPRAS_OUT_M3,TOT_COMPRAS_TX_OUT_M3,MONTO_COMPRAS_OUT_M4,TOT_COMPRAS_TX_OUT_M4,MONTO_COMPRAS_OUT_M5,TOT_COMPRAS_TX_OUT_M5,MONTO_COMPRAS_OUT_M6,TOT_COMPRAS_TX_OUT_M6,MONTO_COMPRAS_OUT_M7,TOT_COMPRAS_TX_OUT_M7,MONTO_COMPRAS_OUT_M8,TOT_COMPRAS_TX_OUT_M8,TOT_NO_USOTX_M8,TOT_NO_USOTX_M7,TOT_NO_USOTX_M6,TOT_NO_USOTX_M5,TOT_NO_USOTX_M4,TOT_NO_USOTX_M3,TOT_NO_USOTX_M2,TOT_NO_USOTX_M1,TOT_NO_USOTX_M0,TOT_NO_USOTX_M_1,TOT_NO_USOTX_M_2,FECHA_NAC_CLIENTE,EDAD,ID_ESTADO_CIVIL,ESTADO_CIVIL,ESCOLARIDAD_DESC,ESCOLARIDAD,CP,ESTADO_ID,GENERO,ID_GENERO,TIPO_VIVIENDA_ID,TIPO_VIVIENDA,OCUPACION_ID,OCUPACION,DEPENDIENTES,ACTIVIDAD_ECONOMICA_ID,ACTIVIDAD_ECONOMICA,HIJOS,TIPO_INGRESO_ID,TIPO_INGRESO,ID_PRODUCTO,PRODUCTO_CRED_DESC,MONTO_DESEMBOLSO,ID_CANAL_DISPERSION,CANAL_DISPERSION,ID_METODO_DISPERSION,METODO_DISPERSION,ID_DIRECCION_REGIONAL,DIRECCION_REGIONAL,COORDENADA_XOS,COORDENADA_YOS,OFICINA_SERVICIO,CENTRO_COSTOS,FLAG_CRD_HIST
330676,9143448,8287599,85229822,3,23,00187721470,2024-07-02,"ACTIVOS, UTILIZADOS",37,MIS AHORROS,185.76,1.00,ACTIVA,2028-03-31,0,1,0,1.00,0,NaN,0,185.84,185.84,185.76,185.72,185.72,185.64,185.60,185.60,185.52,185.48,185.48,185.84,185.80,185.75,185.72,185.68,185.63,185.60,185.56,185.51,185.48,185.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,0.00,1.00,2.00,0.00,1.00,2.00,0.00,1.00,2.00,0.00,1979-11-14,46,4,DIVORCIADO,PRIMARIA,1,27444,7,FEMENINO,2,3,FAMILIAR,2,COMERCIANTE,1,2071017,FABRICACION DE PAN Y PASTELES,4,10,APOYO FAMILIAR,170.00,CRÉDITO GRUPAL,34003.85,554.00,BANCO COMPARTAMOS,3.00,TARJETA DE DEBITO,14164278,DR VENTAS NORESTE,25.53,-103.23,30031153,1230031153,1
334286,9143448,8287599,85230879,3,23,00187722528,2024-07-02,"ACTIVOS, UTILIZADOS",64,CUENTA NIVEL 2 EXPRESS,33.62,1.00,ACTIVA,2027-03-31,1,0,0,1.00,0,NaN,0,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,33.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1979-11-14,46,4,DIVORCIADO,PRIMARIA,1,27444,7,FEMENINO,2,3,FAMILIAR,2,COMERCIANTE,1,2071017,FABRICACION DE PAN Y PASTELES,4,10,APOYO FAMILIAR,170.00,CRÉDITO GRUPAL,34003.85,554.00,BANCO COMPARTAMOS,3.00,TARJETA DE DEBITO,14164278,DR VENTAS NORESTE,25.53,-103.23,30031153,1230031153,1

## Revision de las key de ambas sabanas

In [8]:
import numpy as np

keys_orig = set(df_prcom_orig['NUM_CLIENTE'])
keys_opt = set(df_prcom_opt['NUM_CLIENTE'])

keys_comunes = keys_orig.intersection(keys_opt)
solo_original = keys_orig - keys_opt
solo_optimizado = keys_opt - keys_orig

print(f"Clientes en ambos datasets: {len(keys_comunes):,}")
print(f"Clientes solo en 'original': {len(solo_original):,}")
print(f"Clientes solo en 'optimizado': {len(solo_optimizado):,}")

Clientes en ambos datasets: 2,731,043
Clientes solo en 'original': 0
Clientes solo en 'optimizado': 0

## Creamos codigo para detectar las diferencias

In [9]:
import datacompy

compare = datacompy.PandasCompare(
    df1=df_prcom_orig[df_prcom_opt.columns],
    df2=df_prcom_opt,
    join_columns=['NUM_CLIENTE', 'ANTIGUEDAD_AHORRO','OFICINA_SERVICIO'],
    df1_name='original',
    df2_name='optimizado',
    abs_tol = 0.0001,
    rel_tol = 0
)

print(compare.report(sample_count = 100))

KeyError: "['COALESCE(TOT_SPEI_TX_IN_M0,0)', 'COALESCE(TOT_SPEI_TX_IN_M1,0)', 'COALESCE(TOT_COMPRAS_TX_OUT_M0,0)', 'COALESCE(TOT_COMPRAS_TX_OUT_M1,0)', 'COALESCE(TOT_COMPRAS_TX_OUT_M2,0)', 'COALESCE(TOT_COMPRAS_TX_OUT_M3,0)', 'COALESCE(TOT_COMPRAS_TX_OUT_M4,0)', 'COALESCE(TOT_COMPRAS_TX_OUT_M5,0)', 'COALESCE(TOT_COMPRAS_TX_OUT_M6,0)', 'COALESCE(TOT_COMPRAS_TX_OUT_M7,0)', 'COALESCE(TOT_COMPRAS_TX_OUT_M8,0)'] not in index"

In [ ]:
df_diferencias = compare.all_mismatch(ignore_matching_cols=True)

In [ ]:
df_diferencias

In [ ]:
df_diferencias.to_excel("tablas_diferencias_propension_compras.xlsx", index=False)

In [ ]:
df_diferencias[df_diferencias['num_cliente']==54399169]